set(CPACK_DEBIAN_PACKAGE_MAINTAINER "$ENV{MAINTAINER_NAME}")
set(CPACK_PACKAGE_DIRECTORY "packages/${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}")
set(CPACK_DEBIAN_PACKAGE_DEPENDS ${PKG_DEPENDS})
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_GENERATOR "DEB;TGZ;ZIP") # Create .deb, .tgz, .zip files
include(CPack)
