# Utility C Library
set(UTILITY utility)
set(UTILITY_SRC ${PROJECT_SOURCE_DIR}/subprojects/utility)
set(UTILITY_HEADERS ${UTILITY_SRC}/include)
set(UTILITY_LIB_PATH ${UTILITY_SRC}/build/release/lib)
set(LIB_UTILITY ${UTILITY_LIB_PATH}/lib${UTILITY}.so)

add_library(${UTILITY} SHARED IMPORTED)
set_property(
TARGET ${UTILITY}
PROPERTY IMPORTED_LOCATION ${LIB_UTILITY})

set_property(
TARGET ${UTILITY}
PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${UTILITY_HEADERS})

if(NOT ${UTILITY})
    message(FATAL_ERROR "${UTILITY} not found!")
endif()
